FROM node:12.2.0-alpine

RUN apk update
RUN apk upgrade --available

RUN mkdir /client
COPY . /client

WORKDIR /client
ENV PATH /client/node_modules/.bin:$PATH
COPY package.json /client/package.json
RUN npm install

ENV NODE_ENV DEV
EXPOSE 80

ENTRYPOINT ["npm", "run", "start"]
